remote_theme: pmarsceill/just-the-docs
color_scheme: theme
search:
  heading_level: 3
aux_links:
  "GitHub":
    - "https://github.com/anantoghosh/new-in-ecma-javascript-cheatsheet"
aux_links_new_tab: true
